repos:
- repo: https://github.com/digitalpulp/pre-commit-php
  rev: 1.4.0
  hooks:
  - id: php-lint-all
- repo: https://github.com/gherynos/pre-commit-java
  rev: v0.2.4
  hooks:
  - id: Checkstyle
- repo: https://github.com/gitleaks/gitleaks
  rev: v8.16.3
  hooks:
  - id: gitleaks
- repo: https://github.com/pocc/pre-commit-hooks
  rev: v1.3.5
  hooks:
  - id: cpplint
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: end-of-file-fixer
  - id: trailing-whitespace
