# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Flutter

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

defaults:
  run:
    shell: bash

jobs:
  test:
    permissions:
      contents: read

    name: Test Flutter ${{ matrix.flutter_version }} on ${{ matrix.os }} with Dart ${{ matrix.dart_version }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        flutter_version: [beta, master]
        dart_version: [stable, beta, dev, main]
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@1b05615854632b887b69ae1be8cbefe72d3ae423 # v2.6.0
        with:
          egress-policy: audit

      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0

      - uses: subosito/flutter-action@48cafc24713cca54bbe03cdc3a423187d413aafa # v2.10.0
        with:
          channel: ${{ matrix.flutter_version }}
          cache: true
          cache-key: 'flutter-:os:-:channel:-:version:-:arch:-:hash:'
          cache-path: '${{ runner.tool_cache }}/flutter/:channel:-:version:-:arch:'
          architecture: x64

      - uses: dart-lang/setup-dart@b64355ae6ca0b5d484f0106a033dd1388965d06d
        with:
          sdk: ${{ matrix.dart_version }}

      - name: Install dependencies
        run: flutter pub get

      # Uncomment this step to verify the use of 'flutter format' on each commit.
      - name: Verify formatting
        run: dart format --output=none --set-exit-if-changed lib/

      # Consider passing '--fatal-infos' for slightly stricter analysis.
      - name: Analyze project source
        run: flutter analyze --fatal-infos

      # Your project will need to have tests in test/ and a dependency on
      # package:test for this step to succeed. Note that Flutter projects will
      # want to change this to 'flutter test'.
      #- name: Run tests
      #  run: flutter test
